01. CREATE A AJAX CALL BACK QUERY

ON BUTTON CREATE DYNAMIC ACTION
    NAME OF DYNAMIC ACTION 
    Validate, Save & Update Data

    EVENT : CLICK


P8_COLLECTION_DATE,P8_EMP_ID,P8_COLLECTION_AMOUT,P8_MEMBER_ID,P8_DEPOSIT_MONEY,P8_DEBT_AMOUNT,P8_DEBT_REMAIN,P8_INST_ID,P8_STATUS,P8_CREATED_BY,P8_CREATED_AT,P8_COLLECTION_MODE