SELECT * FROM v$sqlarea;
SELECT * FROM v$sqlstats;
SELECT * FROM v$sql;
SELECT * FROM v$sql_plan;
SELECT * FROM v$sql_workarea;
SELECT * FROM v$sql_plan_statistics;
SELECT * FROM v$sql_plan_statistics_all;
 
 SELECT s.prod_id
  FROM sales s, customers c
  WHERE s.cust_id = c.cust_id;
 
select * from v$sql;
select * from v$sql where sql_text like '%SELECT s.prod_id 
                                           FROM sales s, customers c 
                                           WHERE s.cust_id = c.cust_id%';
select * from v$sql where sql_text like '%SELECT s.prod_id FROM sales s, customers c WHERE s.cust_id = c.cust_id%';
 
 SELECT /* my query */ s.prod_id
  FROM sales s, customers c
  WHERE s.cust_id = c.cust_id;
 
select * from v$sql where sql_text like '%my query%';
select * from v$sql_plan where sql_id = '';
select * from table(dbms_xplan.display_cursor(''));



1.EXEC DBMS_STATS.GATHER_ALL_STATS:
2.v$sql
3.TOP TO BOTTOM RIGHT TO LEFT
4.DISC STATISTICS
5. SET AUTOTRACE ON EXPLAIN 
6.I/O COST DIRECTLY

7.WILL GENERATE SYSTEM STATISTICS => ALL
8.AUX_STATS$
9.THE DATABASE FOLLOW EXACTLY THESESTEPS
10. OUTPUT EXPLAIN: => ALL  