create or replace TYPE GET_MONTH_YEAR AS OBJECT (SRL_NO NUMBER, MNYR_ID NUMBER, MNYR_DISP VARCHAR2(100), MN NUMBER, YR NUMBER)
/

create or replace TYPE GET_MONTH_YEAR_TAB AS TABLE OF GET_MONTH_YEAR
/

create or replace FUNCTION GET_MONTH_YEAR_LIST (pDATE_FROM DATE, pDATE_TO DATE, pFORMAT VARCHAR2)
RETURN GET_MONTH_YEAR_TAB
PIPELINED
IS

BEGIN

    FOR I IN (
                SELECT  ROWNUM RID, A.MNTH, A.MNYRID, DECODE (A.MN,1,55,2,56,3,57,4,58,5,59,6,60,7,61,8,62,9,63,10,64,11,65,12,66,'') MN,  A.YR
                  FROM (SELECT DISTINCT
                               TO_CHAR (ADD_MONTHS (pDATE_FROM, LEVEL - 1), pFORMAT) MNTH,
                               TO_NUMBER (TO_CHAR (ADD_MONTHS (pDATE_FROM, LEVEL - 1), 'RRMM')) MNYRID,
                               TO_NUMBER (TO_CHAR (ADD_MONTHS (pDATE_FROM, LEVEL - 1), 'MM')) MN,
                               TO_NUMBER (TO_CHAR (ADD_MONTHS (pDATE_FROM, LEVEL - 1), 'RRRR')) YR
                          FROM DUAL
                       CONNECT BY LEVEL <= CEIL (MONTHS_BETWEEN (pDATE_TO, pDATE_FROM))
                         ORDER BY TO_NUMBER (TO_CHAR (ADD_MONTHS (pDATE_FROM, LEVEL - 1), 'RRMM'))) A
    ) LOOP

        PIPE ROW (GET_MONTH_YEAR (I.RID, I.MNYRID, I.MNTH, I.MN, I.YR));

    END LOOP;

END GET_MONTH_YEAR_LIST;
/