NAME : BLOOD GROUP
SQL: 

SELECT ELEMENT_NAME AS D, ELEMENT_ID AS R 
 FROM ADM_CODE_ELEMENTS 
WHERE STATUS = 1
  AND CODE_ID = 32;



NAME : COLLECTION METHOD
SQL:

SELECT ELEMENT_NAME AS D, ELEMENT_ID AS R
FROM ADM_CODE_ELEMENTS 
WHERE STATUS = 1
AND CODE_ID = 33;



NAME : GENDER
SQL:

SELECT ELEMENT_NAME AS D, ELEMENT_ID AS R 
 FROM ADM_CODE_ELEMENTS 
WHERE STATUS = 1
  AND CODE_ID = 29;



  
NAME : INSTITUTE NAME
SQL:

SELECT INST_NAME AS D, INST_ID AS R
FROM ADM_INSTITUTE
WHERE STATUS = 1







NAME : MARITAL STATUS
SQL:

SELECT ELEMENT_NAME AS D, ELEMENT_ID AS R 
 FROM ADM_CODE_ELEMENTS 
WHERE STATUS = 1
  AND CODE_ID = 28







NAME : MEMBER
SQL:


SELECT MEMBER_NAME AS D, MEMBER_ID AS R
FROM VV_MEMBER
WHERE STATUS = 1






NAME : MONTH LIST
SQL:


SELECT ELEMENT_NAME, ELEMENT_ID 
FROM ADM_CODE_ELEMENTS 
WHERE CODE_ID = 34
AND STATUS = 1






NAME : PAGE_NAME
SQL: 

---- please replace workspace and application id

  SELECT  PAGE_ID||' - '||PAGE_NAME PAGE_NAME, PAGE_ID 
FROM  APEX_APPLICATION_PAGES
WHERE WORKSPACE  = '01918237902' AND PAGE_ID BETWEEN 1 AND 999
AND APPLICATION_ID = '172344' --AND UPPER(PAGE_TEMPLATE)	 <> UPPER('Modal Dialog')


NAME : RELIGIONS
SQL:

SELECT ELEMENT_NAME AS D, ELEMENT_ID AS R 
 FROM ADM_CODE_ELEMENTS 
WHERE STATUS = 1
  AND CODE_ID = 30







NAME : USER TYPES
SQL:

SELECT ELEMENT_NAME AS D, ELEMENT_NAME AS R
FROM ADM_CODE_ELEMENTS
WHERE STATUS = 1
AND CODE_ID = 26





NAME : USERS
SQL:

SELECT EMP_NAME AS D, EMP_ID AS R
FROM EMP_USERS
WHERE STATUS = 1





NAME : USER_ROLE
SQL:


SELECT   ELEMENT_NAME D, ELEMENT_ID R
  FROM ADM_CODE_ELEMENTS
WHERE CODE_ID = 26
  AND STATUS = 1; 


NAME : MEMBER LIST  -- WHICH HAVE COLLECTION 

SQL:

SELECT VM.MEMBER_NAME D, VM.MEMBER_ID R --, NVL(COL.COL_AMT,0) COL_AMT, COL.WITHDRAW_AMT
FROM VV_MEMBER VM
LEFT JOIN (
        SELECT DC.MEMBER_ID, SUM(NVL(DC.COLLECTION_AMOUT,0)) COL_AMT, SUM(NVL(WITHDRAW_AMT,0)) WITHDRAW_AMT
        FROM VV_DAILY_COLLECTION DC
        LEFT JOIN VV_COLL_WITHDRAW CW ON CW.MEMBER_ID = DC.MEMBER_ID
        GROUP BY DC.MEMBER_ID
) COL ON COL.MEMBER_ID= VM.MEMBER_ID
WHERE NVL(COL.COL_AMT,0) > NVL(COL.WITHDRAW_AMT,0)
AND VM.STATUS = '1';


ADD MEMBER: SCREEN REPORT: 
SQL:


select VM.MEMBER_ID,
       VM.MEMBER_NAME,
       VM.ACCOUNT_NO,
       VM.JOINING_DATE,
       VM.MEMBER_ADDRESS,
       VM.INST_ID,
       DECODE(NVL( VM.STATUS, 1), '1', 'fa fa-check-circle', 'fa fa-times-circle') STATUS_ICON,
       DECODE(NVL( VM.STATUS, 0), '1', 'green', 'red') STATUS_ICON_FLAG,
       VM.STATUS,
       VM.CREATED_BY,
       EU.EMP_NAME,
       VM.CREATED_AT,
       VM.UPDATED_BY,
       VM.UPDATED_AT,
       (CASE WHEN VPL.STATUS = 1 THEN 'YES' ELSE 'NO' END) APPLY_LOAN_STATUS,
       --(CASE WHEN VPL.STATUS = 1 THEN 'YES' ELSE 'NO' END) LOAN_TAKEN,
       CASE WHEN (CASE WHEN VPL.STATUS = '1' THEN 'YES' ELSE 'NO' END)= 'YES' THEN 'green' ELSE 'red' END THE_COLOR,
       ' ' APPLY_LOAN
  from VV_MEMBER VM
  LEFT JOIN EMP_USERS EU ON EU.EMP_ID = VM.CREATED_BY
  LEFT JOIN VV_APPLY_LOAN VPL ON VPL.MEMBER_ID = VM.MEMBER_ID AND VPL.STATUS = 1

